### ISSUE TITLE
[Bug]: Using a change log file that in build directory is not found. 

### ISSUE THREAD

**Issue by mysticdrew** [modrinth/minotaur#24]
We use a changelog file that is processed during the build cycle with token replacement. So the file does not exist in the build directory until the build task is run.
When the changelog file is set as follows.  
`changelog = file('/build/doc/changelog.html').text`
Any gradle task fails due to file not found error. 
I have set it so the modrinth task depends on the build task, so the file should not even be checked until the task is run. 

 - mc 1.16.5 
 - Gradle Version: gradle-7.1.1
 - Minotaur Version: 2.+
 
```
tasks.modrinth.dependsOn(tasks.build)
modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "lfHFW1mp"
    versionNumber = "${version}"
    versionType = "release"
    uploadFile = jar
    gameVersions = ["${project.minecraft_version}"]
    loaders = ["forge"]
    changelog = file('/build/doc/changelog.html').text
}
```
Current workaround
`changelog = file('/build/doc/changelog.html').exists() ? file('/build/doc/changelog.html').text : null`

**Comment by jpenilla** [comment]
When my PR is merged you will need to set it like
```kotlin
changelog.set(
  tasks.producingTask.flatMap {
    it.[output directory property].file("path in output dir").map { f -> f.asFile.readText() }
  }
)
```
or
```kotlin
changelog.set(
  tasks.producingTask.flatMap {
    it.[output file property for changelog].map { f -> f.asFile.readText() }
  }
)
```
for the auto-task dependency wiring, depending on how your producer task works. We won't be able to guess task dependencies if you just use `file(String).text`.

**Comment by mysticdrew** [comment]
I am having trouble getting this to work. 
This is how we produce our changelog. 

```
task processDocs(type: Copy) {
    // update docs
    from(file("$rootDir/doc/")) {
        include '*.html'
        expand 'version': modVersion,
                'date': getDate(),
                'mcversion': project.minecraft_version,
                'loaderversion': project.loader_version,
                'loadername': project.loader_name,
                'apiversion': project.journeymap_api_version
    }
    into "$project.buildDir/doc"
}
```
