### ISSUE TITLE
Using Project ID in dependencies that isn't existed in the Modrinth doesn't give a proper error or reason

### ISSUE THREAD

**Issue by SteveKunG** [modrinth/minotaur#35]
### Describe the bug

Gradle : 7.6
Minotaur : 2.5.0

I've reported and discuss this issue for a few months ago in the Discord, This bug still happen if you put a project in dependencies that does not exist on the Modrinth.

More details here :
https://discord.com/channels/734077874708938864/783153806531100673/992813477712384030

### Steps to reproduce

1. Put a random Project ID to dependencies block, for example : "configured"
```
dependencies {
        required.project "cloth-config"
        required.project "configured"
}
```
2. Run "modrinth" task in the debug mode.
3. See the error below.

```
Project ID resolution for configured failed! Status: 404 Error: null Reason: null

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':forge:modrinth'.
> Failed to upload file to Modrinth! Project ID resolution for configured failed! Status: 404 Error: null Reason: null
```

### Expected behavior

Minotaur should display a proper reason or an error if a project doesn't exist in the Modrinth.

**Comment by triphora** [comment]
Is that not a proper error? `Project ID resolution for configured failed`, it failed to resolve the project ID `configured`

**Comment by SteveKunG** [comment]
Oh, sorry I was confused. A message should put quotes on the Project ID like this `Project ID resolution for "configured" failed`.
Also what about `Status: 404 Error: null Reason: null`?

**Comment by triphora** [comment]
The former part is Minotaur's conclusion, the latter part is the Modrinth server's response. I can make that more clear, though. Not going to release it right now, but it will be included in the next release.

**Comment by triphora** [comment]
Actually, according to the [backend source code](https://github.com/modrinth/labrinth/blob/master/src/routes/projects.rs#L91), that route never returns an error body, only ever null or the expected response. So I can remove that part entirely.
