### ISSUE TITLE
How do I set an environment property in Gradle for my token?

### ISSUE THREAD

**Issue by ghost** [modrinth/minotaur#4]

**Comment by dexman545** [comment]
In gradle, use `token = System.getenv("MODRINTH")`.

 Do set it, it depends on how you run it. Gradle can accept them via the command line, you can also set them in github actions workflow, or as part of Idea's run configuration.

You can see https://github.com/dexman545/Fabric-Autoswitch for an example with github actions.

**Comment by ghost** [comment]
> In gradle, use `token = System.getenv("MODRINTH")`.
> 
>  Do set it, it depends on how you run it. Gradle can accept them via the command line, you can also set them in github actions workflow, or as part of Idea's run configuration.
> 
> You can see https://github.com/dexman545/Fabric-Autoswitch for an example with github actions. 

Thank you
