### ISSUE TITLE
Failed to upload file to Modrinth! java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by axieum** [modrinth/minotaur#50]
### Describe the bug

```
> Task :modrinth
Minotaur: 2.7.5

...

* What went wrong:
Execution failed for task ':modrinth'.
> Failed to upload file to Modrinth! java.net.SocketTimeoutException: timeout
```

This occurs when publishing both locally and via GitHub actions.

### Expected behavior

To upload successfully.

### Additional context

https://github.com/axieum/minecord/actions/runs/5208250157/jobs/9396631869

**Comment by axieum** [comment]
It appears to still have uploaded however? https://modrinth.com/mod/minecord/version/2.0.0+1.20
Strange.

**Comment by triphora** [comment]
If it went through, I wouldn't worry about it - likely a one-off fluke.

**Comment by Rakambda** [comment]
Actually happened to me too https://github.com/Rakambda/FallingTree/actions/runs/5212670063/jobs/9406588782 though file wasn't published

**Comment by rubensworks** [comment]
This has been happening to all my builds as of today, for example: https://github.com/CyclopsMC/IntegratedDynamics/actions/runs/13117551655/job/36595442706
