### ISSUE TITLE
Doesn't work with buildscript

### ISSUE THREAD

**Issue by Enaium** [modrinth/minotaur#51]
### Describe the bug

I have configured buildscript

```kotlin
plugins {
    id("java")
}

buildscript {
    repositories {
        maven {
            name = "Fabric"
            url = uri("https://maven.fabricmc.net/")
        }
        gradlePluginPortal()
        mavenCentral()
    }

    val loomVersion: String by project
    val minotaurVersion: String by project

    dependencies {
        classpath("net.fabricmc:fabric-loom:${loomVersion}")
        classpath("com.modrinth.minotaur:Minotaur:${minotaurVersion}")
    }
}
```

I have a multi project, but it doesn't work like fabric as work

```kotlin
subprojects {
    apply {
        plugin("java")
        plugin("fabric-loom")
        plugin("com.modrinth.minotaur")
    }

    //Unresolved reference: modrinth
    modrinth {

    }
}
```

**Comment by triphora** [comment]
Please use the Discord for support https://discord.gg/modrinth-734077874708938864

**Comment by Enaium** [comment]
> Please use the Discord for support https://discord.gg/modrinth-734077874708938864

If you do not accept bugs, you should **disabling issues** of this repository.

**Comment by triphora** [comment]
We accept bugs, but I doubt this is a bug considering there is no reliable way to reproduce it, thus please ask for support, don't assume it's a bug just because it's not working for you.
