### ISSUE TITLE
Support new NeoForge userdev plugin.

### ISSUE THREAD

**Issue by Darkhax** [modrinth/minotaur#59]
### Is your suggested enhancement related to a problem? Please describe.

Minotaurs automatic detection does not have integration for NeoForge's new userdev plugin. 

### Describe the solution you'd like

Add the new plugin ID `net.neoforged.gradle.userdev` to the pluginLoaderMap. Their old plugin ID is still in use so both should be supported for now.

### Describe alternatives you've considered

I am currently setting the properties manually. 

### Additional context

The solution mentioned is the same fix I used in CurseForgeGradle which had the same issue. 

When trying to deploy with Minotaur I noticed the NeoForge upload was also missing a game version. Additional changes will likely be needed for this as well.

**Comment by Darkhax** [comment]
Thanks for looking into this. The new fix seems to work for the loader, although the game version detection fails. 

> Caused by: org.gradle.api.GradleException: Failed to upload file to Modrinth! Cannot get property 'MC_VERSION' on extra properties extension as it does not exist
	at com.modrinth.minotaur.TaskModrinthUpload.apply(TaskModrinthUpload.java:262)

**Comment by triphora** [comment]
Let me know if this is still a problem in v2.8.6. I'm unable to get a working NeoForge dev env locally, regardless of whether Minotaur is involved.

**Comment by triphora** [comment]
Closing since no response, assuming resolved.
