### ISSUE TITLE
Some Minotaur fields are private marked despite being listed in readme as user facing

### ISSUE THREAD

**Issue by TelepathicGrunt** [modrinth/minotaur#60]
### Describe the bug

Gradle produces warning that gameVersions and loaders are private fields in Minotaur
![image](https://github.com/modrinth/minotaur/assets/40846040/e2445be0-5883-4780-838d-91e280007828)

Can still build just file and upload through Minotaur.

### Steps to reproduce

Make a project that sets the two fields like Bumblezone 
https://github.com/TelepathicGrunt/Bumblezone/tree/1.20-Arch

### Expected behavior

Fields are marked public if user facing as shown by the readme here:
https://github.com/modrinth/minotaur

**Comment by triphora** [comment]
This warning is entirely inaccurate, since Groovy converts it to using the get/set calls anyway... it's times like this I hate IntelliJ
