### ISSUE TITLE
Cant have ["fabric"] in loaders array when using quilt

### ISSUE THREAD

**Issue by ghost** [modrinth/minotaur#65]
### Describe the bug

When using loaders = ["quilt", "fabric"] you will get an error for not having a fabric.mod.json even though you are on quilt.

### Steps to reproduce

1. Set your array to loaders = ["quilt", "fabric"]
2. Run the "modrinth" publishing task

### Expected behavior

The JAR to be uploaded.

**Comment by ricksouth** [comment]
Fabric can't load Quilt mods. So if you're saying it's compatible with Fabric, it must contain a `fabric.mod.json` file. You can load Fabric mods on Quilt.

**Comment by ghost** [comment]
Oh yeah im stupid
